project_id = "gvoyhkipucdtgixzultj"

[functions.chat]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.enrich-lusha-contact]
verify_jwt = false

[functions.enrich-hunter-contact]
verify_jwt = false

[functions.hunter-domain-search]
verify_jwt = false
