project_id = "gvoyhkipucdtgixzultj"

[functions.chat]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.enrich-lusha-contact]
verify_jwt = false

[functions.enrich-hunter-contact]
verify_jwt = false

[functions.hunter-domain-search]
verify_jwt = false

[functions.enrich-apollo-contact]
verify_jwt = false

[functions.bulk-enrich]
verify_jwt = false

[functions.enrich-findymail-contact]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-qr]
verify_jwt = false

[functions.detect-bounces]
verify_jwt = false

[functions.sync-emails]
verify_jwt = false

[functions.test-connector]
verify_jwt = false

[functions.test-email-connection]
verify_jwt = false

[functions.prospector-search]
verify_jwt = false

[functions.get-api-usage]
verify_jwt = false

[functions.suggest-reply]
verify_jwt = false
